title: <p align="center"> Pavan Kumar K </p>
logo: /assets/img/Pavan.jpg

description:
  <p align="center">
  <a href="pdf/PavanKumar.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/pavan-kumar-kamisetti-92254926a/">LinkedIn</a> |
  <a href="https://github.com/kpavan3697">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Worked with IBM Research at Big Data Analytics team.
  Working in AdTech domain for 3 years.
  <br>
  </p>



theme: jekyll-theme-minimal
